name: Build and push to Scaleway registry - Production

on:
  push:
    branches: [main]
    paths:
      - 'back/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to registry
        run: echo ${{ secrets.SCALEWAY_SECRET_KEY }} | docker login rg.fr-par.scw.cloud/krirogn-busquery -u nologin --password-stdin
      - name: Create DB env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
      - name: Build and tag the Docker image
        run: docker build -t rg.fr-par.scw.cloud/krirogn-busquery/busquery-api:latest .
      - name: Push the Docker image to the registry
        run: docker push rg.fr-par.scw.cloud/krirogn-busquery/busquery-api:latest
